/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://hb5s63olxjcw7owb5udr4kwcei.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bi3sjowmvvdopmguzoznfidgki",
    "aws_cognito_identity_pool_id": "eu-central-1:d95dcf5f-cb08-473e-af89-8e851cd51e23",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_EWi8Ds9ak",
    "aws_user_pools_web_client_id": "5jev08bktqlf3e7afahg6vfpii",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
